cask 'font-skolasans' do
  version '1.000'
  sha256 '52affe1fdf66ae8484bf32711f6dd2e2789b63966065e6061ca6bad9fa6e6187'

  # download1265.mediafire.com was verified as official when first introduced to the cask
  url 'https://download1265.mediafire.com/cmlgmdh4j6bg/5cbb1kb41ypzm3v/SkolaSansPro.zip'
  name 'SkolaSans Pro'
  homepage 'https://www.behance.net/gallery/17504367/Free-font-family-SkolaSans'

  font 'SkolaSans Pro OTF/SkolaSans-Black.otf'
  font 'SkolaSans Pro OTF/SkolaSans-BlackItalic.otf'
  font 'SkolaSans Pro OTF/SkolaSans-Bold.otf'
  font 'SkolaSans Pro OTF/SkolaSans-BoldItalic.otf'
  font 'SkolaSans Pro OTF/SkolaSans-Light.otf'
  font 'SkolaSans Pro OTF/SkolaSans-LightItalic.otf'
  font 'SkolaSans Pro OTF/SkolaSans-Medium.otf'
  font 'SkolaSans Pro OTF/SkolaSans-MediumItalic.otf'
  font 'SkolaSans Pro OTF/SkolaSans-Regular.otf'
  font 'SkolaSans Pro OTF/SkolaSans-RegularItalic.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-Black.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-BlackItalic.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-Bold.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-BoldItalic.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-Light.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-LightItalic.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-Medium.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-MediumItalic.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-Regular.otf'
  font 'SkolaSansCn Pro OTF/SkolaSansCn-RegularItalic.otf'
end
